// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsnZNYqnguSJvkBpavKOXcB3MfVOnMafE',
    appId: '1:856343090062:web:fd12a5fc3a6c10f69e8adf',
    messagingSenderId: '856343090062',
    projectId: 'stayease-d24db',
    authDomain: 'stayease-d24db.firebaseapp.com',
    storageBucket: 'stayease-d24db.firebasestorage.app',
    measurementId: 'G-0M64K2XBV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDZGau4uK040MhatG2kesyRUVtMkIx4_Q',
    appId: '1:856343090062:android:953b76041c68b21a9e8adf',
    messagingSenderId: '856343090062',
    projectId: 'stayease-d24db',
    storageBucket: 'stayease-d24db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVke0T6hqSoZyPM1X-m5tvi2lbTLBiogY',
    appId: '1:856343090062:ios:d9257bdd88406dff9e8adf',
    messagingSenderId: '856343090062',
    projectId: 'stayease-d24db',
    storageBucket: 'stayease-d24db.firebasestorage.app',
    iosBundleId: 'com.example.stayease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVke0T6hqSoZyPM1X-m5tvi2lbTLBiogY',
    appId: '1:856343090062:ios:d9257bdd88406dff9e8adf',
    messagingSenderId: '856343090062',
    projectId: 'stayease-d24db',
    storageBucket: 'stayease-d24db.firebasestorage.app',
    iosBundleId: 'com.example.stayease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsnZNYqnguSJvkBpavKOXcB3MfVOnMafE',
    appId: '1:856343090062:web:8422b0359b24f5e69e8adf',
    messagingSenderId: '856343090062',
    projectId: 'stayease-d24db',
    authDomain: 'stayease-d24db.firebaseapp.com',
    storageBucket: 'stayease-d24db.firebasestorage.app',
    measurementId: 'G-FQEX4NQ42X',
  );
}
